### ISSUE TITLE
Where is the gantt view button

### ISSUE THREAD

**Issue by OpencloudPro** [funbaker/odoo-web_gantt#8]
I was trying to test this but i can not find the gantt view button. Is it stil not available? Thanks

**Comment by funbaker** [comment]
In the Community Edition, there is no gantt view defined by default. This has to be done in a separate module (e.g. https://github.com/funbaker/odoo_funbaker/tree/master/project_extended )

**Comment by OpencloudPro** [comment]
I tought that was what your module did. What is the function of this APP
then?

A ter, 7/06/2016, 10:38, Stefan Becker notifications@github.com escreveu:

**Comment by funbaker** [comment]
Providing the gantt view type, like a library.
Implementing is not (or should not be) part of this module.
Im thinking about integrating it into the repository as another module though.

**Comment by funbaker** [comment]
Added this for the project module.
https://github.com/humanilog/odoo-web_gantt/commit/f7dca1d6835128bf3868c94c7ec4f57999005bad
